#!/bin/bash
# USAGE: change_version MAJOR MINOR [REV]

MAJOR=$1
MINOR=$2
RELEASE=$3

function change_file {
	local file_name=$1
	local sed_pattern=$2
	
	echo -e "========================================================="
	echo "Changing ${file_name}..."
	cp "${file_name}" "${file_name}.bak"
	sed -e "${sed_pattern}" "${file_name}.bak" > "${file_name}"
	diff "${file_name}.bak" "${file_name}"
}

change_file src/nmapps/__init__.py "s/\(\s*__version__\s*\=\s*\)\"[^\"]*\"/\1\"$MAJOR.${MINOR}${RELEASE}\"/g"
change_file doc/conf.py            "s/\(\s*version\s*\=\s*\)\"[^\"]*\"/\1\"${MAJOR}.${MINOR}\"/g"
change_file doc/conf.py            "s/\(\s*release\s*\=\s*\)\"[^\"]*\"/\1\"${MAJOR}.${MINOR}${RELEASE}\"/g"

